### ISSUE TITLE
mäng ei avane

### ISSUE THREAD

**Issue by raitnigol** [AlaenKermit/hist-comment#1]
tere, mäng ei avane? kasutan arch linux muidu

**Comment by AlaenKermit** [comment]
Hello there Rait, unfortunately the development for the game has ended due to lack of funds and now I must find another job that I can do.
ps. Jüri Ratas announced that he will be resigning.
A sad day indeed.

**Comment by AlaenKermit** [comment]
Nevermind, everything is cool.
Thank you in advance.
